apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cnsrun-frontend
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
#    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/binary-authorization: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '2'
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/network-interfaces: '[{"network":"cnsrun-app", "subnetwork":"cnsrun-cloudrun-hands-on-473403"}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      serviceAccountName: cnsrun-app-frontend@cloudrun-hands-on-473403.iam.gserviceaccount.com
      containers:
      - image: frontend
        env:
          - name: BACKEND_FQDN
            value: "https://cnsrun-backend-6okavf474q-an.a.run.app" # FIXME: Change BACKEND_FQDN value after backend resources is created
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
          tcpSocket:
            port: 8080

