version: "3"

silent: true

dotenv: [".env"]

tasks:
  setup:
    desc: Setup environment variables in shell config
    cmds: 
      - echo 'export GOOGLE_CLOUD_PROJECT={{.GOOGLE_CLOUD_PROJECT}}' >> ~/.zshrc
      - echo "Added GOOGLE_CLOUD_PROJECT to ~/.zshrc. Run 'source ~/.zshrc' or restart your terminal to apply."
      - gcloud auth application-default login
      - gcloud config set project {{.GOOGLE_CLOUD_PROJECT}}

  fmt:
    desc: Format terraform files
    cmds:
      - terraform fmt -recursive

  build-push-frontend:
    desc: Build and push frontend container image
    cmds:
      - cd app/frontend && docker build --platform linux/amd64 -t asia-northeast1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/cnsrun-app/frontend:v1 .
      - docker push asia-northeast1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/cnsrun-app/frontend:v1

  build-push-backend:
    desc: Build and push backend container image
    cmds:
      - cd app/backend && docker build --platform linux/amd64 -t asia-northeast1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/cnsrun-app/backend:v1 .
      - docker push asia-northeast1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/cnsrun-app/backend:v1

  build-push-batch:
    desc: Build and push batch container image
    cmds:
      - cd app/batch && docker build --platform linux/amd64 -t asia-northeast1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/cnsrun-app/batch:v1 .
      - docker push asia-northeast1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/cnsrun-app/batch:v1

  build-push-all:
    desc: Build and push all container images
    cmds:
      - task: build-push-frontend
      - task: build-push-backend
      - task: build-push-batch

  deploy-backend:
    desc: Apply Cloud Deploy pipeline for backend
    cmds:
      - sed -e "s/PROJECT_ID/${GOOGLE_CLOUD_PROJECT}/g" doc/clouddeploy.yml | sed -e "s/REGION/asia-northeast1/g" | sed -e "s/SERVICE_NAME/cnsrun-backend/g" > /tmp/clouddeploy_backend.yml
      - gcloud deploy apply --file=/tmp/clouddeploy_backend.yml --region asia-northeast1

  deploy-frontend:
    desc: Apply Cloud Deploy pipeline for frontend
    cmds:
      - sed -e "s/PROJECT_ID/${GOOGLE_CLOUD_PROJECT}/g" doc/clouddeploy.yml | sed -e "s/REGION/asia-northeast1/g" | sed -e "s/SERVICE_NAME/cnsrun-frontend/g" > /tmp/clouddeploy_frontend.yml
      - gcloud deploy apply --file=/tmp/clouddeploy_frontend.yml --region asia-northeast1

  deploy-batch:
    desc: Apply Cloud Deploy pipeline for batch
    cmds:
      - sed -e "s/PROJECT_ID/${GOOGLE_CLOUD_PROJECT}/g" doc/clouddeploy.yml | sed -e "s/REGION/asia-northeast1/g" | sed -e "s/SERVICE_NAME/cnsrun-batch/g" > /tmp/clouddeploy_batch.yml
      - gcloud deploy apply --file=/tmp/clouddeploy_batch.yml --region asia-northeast1

  deploy-all:
    desc: Apply Cloud Deploy pipelines for all services
    cmds:
      - task: deploy-backend
      - task: deploy-frontend
      - task: deploy-batch

  run-deploy-frontend:
    desc: Deploy frontend to Cloud Run
    cmds:
      - gcloud run deploy cnsrun-frontend --image=asia-northeast1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/cnsrun-app/frontend:v1 --allow-unauthenticated --service-account=cnsrun-app-frontend --region=asia-northeast1

  run-deploy-backend:
    desc: Deploy backend to Cloud Run
    cmds:
      - gcloud run deploy cnsrun-backend --image=asia-northeast1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/cnsrun-app/backend:v1 --service-account=cnsrun-app-backend --region=asia-northeast1

  run-deploy-batch:
    desc: Deploy batch to Cloud Run Jobs
    cmds:
      - gcloud run jobs deploy cnsrun-batch --image=asia-northeast1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/cnsrun-app/batch:v1 --service-account=cnsrun-app-batch --region=asia-northeast1

  run-deploy-all:
    desc: Deploy all services to Cloud Run
    cmds:
      - task: run-deploy-frontend
      - task: run-deploy-backend
      - task: run-deploy-batch

  run-delete-frontend:
    desc: Delete frontend service from Cloud Run
    cmds:
      - gcloud run services delete cnsrun-frontend --region=asia-northeast1 --quiet

  run-delete-backend:
    desc: Delete backend service from Cloud Run
    cmds:
      - gcloud run services delete cnsrun-backend --region=asia-northeast1 --quiet

  run-delete-batch:
    desc: Delete batch job from Cloud Run
    cmds:
      - gcloud run jobs delete cnsrun-batch --region=asia-northeast1 --quiet

  run-delete-all:
    desc: Delete all services and jobs from Cloud Run
    cmds:
      - task: run-delete-frontend
      - task: run-delete-backend
      - task: run-delete-batch
